In [4]:
import numpy as np
arr=[[1,2,3,4],[3,4,5,6],[7,8,9,6],[12,7,10,9],[2,11,8,10]]
narr=np.array(arr)

In [5]:
print(narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [12  7 10  9]
 [ 2 11  8 10]]


In [9]:
print(narr.sum(axis=1))
narr[1]


[10 18 30 38 31]


array([3, 4, 5, 6])

In [21]:
narr.reshape(2,10)
narr.mean(axis=1)

array([ 2.5 ,  4.5 ,  7.5 ,  9.5 ,  7.75])

In [24]:
np.std(narr,axis=1)

array([ 1.11803399,  1.11803399,  1.11803399,  1.80277564,  3.49106001])

In [ ]:
np.median(narr,axis=1)

In [25]:
np.percentile(narr,25,axis=1)

array([ 1.75,  3.75,  6.75,  8.5 ,  6.5 ])