## Numpy is an n dimensional array object or ** ndarray ** 
## which provides a fast and efficent way of storing homogenous data

## we can have ndarray with 1 dimension or 1 row and these are rank 1 arrays
## or we can have multi-dimnesional rarrays with more than one row [[row1, row2],[row3,row4]]

In [1]:
import numpy as np

In [2]:
##Rank 1 array

arr1=[3,4,5,6,7]

print(type(arr1))

<class 'list'>


In [3]:
arr1=[[1,2,3]]

[3, 4, 5, 6, 7]


In [4]:
narr1=np.array(arr1)

In [5]:
print(type(narr1))

<class 'numpy.ndarray'>


In [6]:
# multidimensional array

arr2=[[1,2,3,4],[3,4,5,6]]

narr2=np.array(arr2)

print(narr2)

[[1 2 3 4]
 [3 4 5 6]]


In [10]:
arr3=[[1,2,3,4],[3,4,5,6],[7,8,9,6]]
print(type(arr3))
narr3=np.array(arr3)
print(type(narr3))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
print(narr3.shape)

(3, 4)


In [8]:
#2*2 array with 0s

zer=np.zeros((2,2))
print(zer)

[[ 0.  0.]
 [ 0.  0.]]


In [15]:
#2*2 array with 5

full=np.full((3,2),5)

print(full)

[[5 5]
 [5 5]
 [5 5]]


In [10]:
ex3 = np.eye(2,2) #diagonal 1
print(ex3)

[[ 1.  0.]
 [ 0.  1.]]


In [11]:
ex3 = np.eye(4,4) #diagonal 1
print(ex3)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [21]:
print(np.zeros((3,3))-np.eye(3,3)/3)

[[-0.33333333  0.          0.        ]
 [ 0.         -0.33333333  0.        ]
 [ 0.          0.         -0.33333333]]
