## Matrix Arithmetic

In [2]:
import numpy as np

In [10]:
x=np.matrix([[1, 2], [3, 4]])

y=np.matrix([[5, 3], [8, 7]])
#Numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional. 
#provide a convenient notation for matrix multiplication

In [14]:
print(y)

[[5 3]
 [8 7]]


In [15]:
print(x)

[[1 2]
 [3 4]]


In [16]:
print(x+y)

[[ 6  5]
 [11 11]]


In [17]:
print(x*3)

[[ 3  6]
 [ 9 12]]


## Subtraction

In [7]:
print(x-y)

[[-4 -1]
 [-5 -3]]


## Multiplication

In [15]:
A=np.matrix([[1, 2], [3, 4]])

print(A)

[[1 2]
 [3 4]]


In [20]:
#haddmard multiplication
print (A*A)

[[ 7 10]
 [15 22]]


In [21]:
#elemant wise multiplication
print(np.multiply(A,A))
A*A


[[ 1  4]
 [ 9 16]]


matrix([[ 7, 10],
        [15, 22]])

## Inverse

In [11]:
from numpy.linalg import inv

In [12]:
print(inv(A))
A.I

NameError: name 'A' is not defined

## Transpose

In [22]:
print(A.T) #flip rows with columns 

[[1 3]
 [2 4]]


In [27]:
x=np.matrix([[2,1],[3,2]])
x

matrix([[2, 1],
        [3, 2]])

In [24]:
c=np.array([[4, 3], [2, 1]])
d=np.array([[1, 2], [3, 4]])
print(c*d)

[[4 6]
 [6 4]]


In [28]:
print(np.dot(c,d))

[[13 20]
 [ 5  8]]


In [10]:
np.matrix(c).I

matrix([[-0.5,  1.5],
        [ 1. , -2. ]])

In [7]:
am=np.array([1,4,2,3])
am
am[:, np.newaxis] 

array([[1],
       [4],
       [2],
       [3]])

In [35]:
A=np.array([[1,4],[6,3]])
b=np.array([1,2])
print(A)
print(b)
np.linalg.solve(A,b)

[[1 4]
 [6 3]]
[1 2]


array([ 0.23809524,  0.19047619])